In [1]:
import pandas as pd
import numpy as np
file = 'Assignment_4_Data_and_Template copy.xlsx'
xl = pd.ExcelFile("./" + file)
df = xl.parse('Training Data')

binarydatalabels = np.array(df.Failure)
typedatalabels = np.array(df.Type)
typedatalabelslist = list(typedatalabels)
tdlexpanded = []
for i in typedatalabelslist :
    if i == 0 :
        tdlexpanded.append([+1, -1, -1, -1 ,-1, -1])
    if i == 1 :
        tdlexpanded.append([-1, +1, -1, -1 ,-1, -1])
    if i == 2 :
        tdlexpanded.append([-1, -1, +1, -1 ,-1, -1])
    if i == 3 :
        tdlexpanded.append([-1, -1, -1, +1, -1, -1])
    if i == 4 :
        tdlexpanded.append([-1, -1, -1 ,-1, +1, -1])
    if i == 5 :
        tdlexpanded.append([-1, -1, -1 ,-1, -1, +1])

expandedarray = np.array(tdlexpanded)
# print (tdlexpanded)
df2 = xl.parse('Training Data', )
df2 = df2.drop(labels='Type',axis=1)
df2 = df2.drop(labels='Failure',axis=1)
featurevectors = np.array(df2.values)
# print(featurevectors)
# print (df2)

binaryclassifier = np.dot(np.linalg.pinv(featurevectors), binarydatalabels)
multiclassifier = np.dot(np.linalg.pinv(featurevectors), expandedarray)

# print (binaryclassifier)
# print (multiclassifier)

df3 = xl.parse('To be classified')
df3 = df3.drop(labels='Type',axis=1)
df3 = df3.drop(labels='Failure',axis=1)
# print(df3)
testingVectors = np.array(df3.values)
# print (testingVectors)
results = []
for i in testingVectors :
    results.append(np.sign(np.dot(i, binaryclassifier)))
# print (results)
resultsa = []
for i in testingVectors :
    resultsa.append(np.dot(i, multiclassifier).argmax(axis=0))
# test_multi_validation = np.dot(test_Xa, multi_W).argmax(axis=1)
# print (resultsa)
rrrrr = []
for i in featurevectors:
    rrrrr.append(np.dot(i, multiclassifier).argmax(axis=0))
# print (rrrrr)
multiconfusionresults = np.zeros([6, 6], dtype=int)
hi = 0
for i in rrrrr :
    hi +=1
print (hi)
for i, j in zip(rrrrr, typedatalabelslist):
#     print (i)
#     print (j)
    multiconfusionresults[j][i] += 1
asdf = []
for i in featurevectors:
    asdf.append(np.sign(np.dot(i, binaryclassifier)))

print(multiconfusionresults)

binaryconfusionresults = np.zeros([2, 2], dtype=int)
for i, j in zip (asdf, binarydatalabels) :
    if (i == -1) :
        i = 0
    if (j == -1) :
        j = 0
    binaryconfusionresults[j][i] += 1

print (binaryconfusionresults)

# har = 0
# for i in binaryconfusionresults:
#     har += i
# print (har)


6600
[[ 652   11  390    1    0   46]
 [   0  739    0  270    0   91]
 [ 216    0  872    0    0   12]
 [  15  532    2  176    0  375]
 [   0    7    0    0 1090    3]
 [  30  256    9   76    4  725]]
[[3229   71]
 [1150 2150]]


/Users/gabrielchen/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:80: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
